import type { Metadata } from "next";
import { Manrope, Inter } from 'next/font/google';
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ['300','400','500','600','700']
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['300','400','500','600','700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${inter.variable} antialiased bg-black text-white`}> 
        {children}
      </body>
    </html>
  );
}
